#!/bin/sh
SERVICE_NAME=CatCamService
PATH_TO_JAR=/home/pi/catcam/
PID_PATH_NAME=/tmp/CatCamService-pid
case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            nohup java -jar $PATH_TO_JAR/PIRcatcam-assembly-3.0.2.jar > $PATH_TO_JAR/$SERVICE_NAME.out 2> $PATH_TO_JAR/$SERVICE_NAME.err < /dev/null &
			echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill $PID;
            echo "$SERVICE_NAME stopped ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    status)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
			if [ ps -ef | grep $PID ]
				echo "[ok] $SERVICE_NAME is running."
			fi 
        else
            echo "$SERVICE_NAME is not running ..."
            exit 1;
        fi
	;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill $PID;
            echo "$SERVICE_NAME stopped ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            nohup java -jar $PATH_TO_JAR/PIRcatcam-assembly-3.0.2.jar > $PATH_TO_JAR/$SERVICE_NAME.out 2> $PATH_TO_JAR/$SERVICE_NAME.err < /dev/null &
            echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac 
